### ISSUE TITLE
Options to force CI server mode

### ISSUE THREAD

**Issue by adamralph** [adamralph/bullseye#127]
`--appveyor`, `--travis`, `--teamcity`

The CI environment is usually detected, but in some cases may not be, e.g. when [running the build in a Docker container](https://github.com/SQLStreamStore/SQLStreamStore/pull/190#issuecomment-428529223).

**Comment by blairconrad** [comment]
Just a thought: `--ci-mode=appveyor` or similar?

**Comment by adamralph** [comment]
@blairconrad I guess that's worth considering. Until now I've been following the precedent set by xunit: 

https://github.com/xunit/xunit/blob/c54cc52ffb275c81afed022521870193bbca6c39/src/xunit.runner.reporters/TeamCityReporter.cs#L14

https://github.com/xunit/xunit/blob/c54cc52ffb275c81afed022521870193bbca6c39/src/xunit.runner.reporters/AppVeyorReporter.cs#L14

**Comment by blairconrad** [comment]
Sure, that makes sense. There's probably no functional difference. Me, I like the grouping, especially since specifying more than one of these flags makes no sense, but I think it's largely just a matter of taste. Thanks for listening!
