### ISSUE TITLE
Enable console colours under Azure Pipelines

### ISSUE THREAD

**Issue by blairconrad** [adamralph/bullseye#150]
Under Bullseye 2.2.0, on Azure pipelines, the build output is not coloured, instead displaying the ANSI escape codes:

![image](https://user-images.githubusercontent.com/3275797/48655857-011c0500-e9eb-11e8-9fa6-fdb01fbbd163.png)

(from https://dev.azure.com/blairconrad/SendComics/_build/results?buildId=9&view=logs)

I'd offer to help, but I am not sure where to start!

**Comment by blairconrad** [comment]
Ah, thanks, @adamralph. I should've thought about the need for ANSI support. I [built with `--verbose`](https://dev.azure.com/blairconrad/SendComics/_build/results?buildId=12&view=logs):

```
2018-11-17T17:20:50.1410759Z Bullseye: Got a handle to the standard output device (GetStdHandle): 2164
2018-11-17T17:20:50.1413863Z Bullseye: Failed to get the current output mode of the console screen buffer (GetConsoleMode). Error code: 6
2018-11-17T17:20:50.1471639Z [36mBullseye[37m: [0m[90mVersion: 2.2.0+2fee2d5f074ee03dea3b0a899551c2da0dd1480d
2018-11-17T17:20:50.1490203Z [36mBullseye[37m: [0m[90mHost: Unknown
2018-11-17T17:20:50.1490465Z [36mBullseye[37m: [0m[90mOS: Windows
2018-11-17T17:20:50.1490824Z [36mBullseye[37m: [0m[90mArgs: --verbose
2018-11-17T17:20:50.1566686Z [36mBullseye[37m: [0m[37mStarting...[97m (default)[0m
2018-11-17T17:20:50.1732460Z [36mBullseye[37m/[36mdefault[37m: [0m[90mWalking dependencies...
2018-11-17T17:20:50.1732867Z [36mBullseye[37m/[36mdefault[37m/[36mtest[37m: [0m[90mWalking dependencies...
2018-11-17T17:20:50.1733134Z [36mBullseye[37m/[36mdefault[37m/[36mtest[37m/[36mbuild[37m: [0m[90mWalking dependencies...
2018-11-17T17:20:50.1733380Z [36mBullseye[37m/[36mdefault[37m/[36mtest[37m/[36mbuild[37m: [0m[90mAwaiting...
2018-11-17T17:20:50.1776379Z [36mBullseye[37m/[36mbuild[37m: [0m[37mStarting...[0m
```

Seems the handle is invalid. Not that surprising, I suppose. There is a [defunct UserVoice request for this feature](https://visualstudio.uservoice.com/forums/330519-azure-devops-formerly-visual-studio-team-services/suggestions/34253173-support-ansi-escape-codes-for-color-in-build-outpu). I can take a peek and see where we request these features now.

**Comment by blairconrad** [comment]
Ah. There's an existing issue. Took some searching. https://github.com/Microsoft/azure-pipelines-agent/issues/1569

**Comment by adamralph** [comment]
> Seems the handle is invalid. Not that surprising, I suppose.

Yeah, I don't think think works on build servers at all. I was more just curious to see the logs. It fails on Appveyor too but Appveyor respects the ANSI codes, so it's fine.

I guess you just need to wait for that issue to be fixed, and perhaps consider the `--no-color` option in the meantime.

**Comment by adamralph** [comment]
Perhaps this could go into an FAQ.

**Comment by blairconrad** [comment]
Yeah, I'll probably turn on `--no-color`. I've also checked out the azure-pipelines-agent, in case I can see an easy way to fix it. (I've low hopes.)

Thanks for your time!

**Comment by adamralph** [comment]
Closing in favour of https://github.com/Microsoft/azure-pipelines-agent/issues/1569.

**Comment by adamralph** [comment]
@blairconrad now that https://github.com/Microsoft/azure-pipelines-agent/issues/1569 has been released, it would be interested to see how your build looks.

**Comment by blairconrad** [comment]
But I've been logged out for over 5 minutes! How will I know?
But seriously, I will push something soonish.

**Comment by blairconrad** [comment]
It is more better! Not quite what I expected, but tonnes more readable. I am a content person.

https://dev.azure.com/blairconrad/SendComics/_build/results?buildId=14

![image](https://user-images.githubusercontent.com/3275797/49962022-14cf6400-fee2-11e8-9653-074b48e38c4f.png)

Thanks!

**Comment by adamralph** [comment]
Definitely an improvement. If I'm not too lazy, I may introduce an [optimised palette](https://github.com/adamralph/bullseye/blob/794fbaee349ab4478921f4d5d51b2faaf28158fc/Bullseye/Internal/Palette.cs#L64-L102) for Azure Piplines.

**Comment by blairconrad** [comment]
Like the one you can see at https://dev.azure.com/blairconrad/blair%20bullseye/_build/results?buildId=18?

(Ignore the bonus environment variables at the top.)

PR coming soon!

**Comment by blairconrad** [comment]
Whoops. I meant to start a PR to my own repo and sent it to yours. #199. Carrying on!

**Comment by tlian** [comment]
Where is this setting to turn off coloring (i.e. --no-color option)?

**Comment by adamralph** [comment]
@tlian if you follow the [quick start](https://github.com/adamralph/bullseye#quick-start) you will see it when you run `dotnet run -- --help`:

```
 -N, --no-color             Disable colored output
```

You can specify it like so:

```
dotnet run -- --no-color`
```

or

```
dotnet run -- -N
```
