### ISSUE TITLE
Log exceptions inside targets

### ISSUE THREAD

**Issue by Mpdreamz** [adamralph/bullseye#162]
## Benefits

- Less scrolling to see the last target which failed (as mentioned below)
- Smaller stack traces, since the exception is being logged further down the stack
- When running with `--parallel`, all exception details are shown.

## Before

![image](https://user-images.githubusercontent.com/677704/49688621-45478480-fb15-11e8-9ba4-232e80597010.png)

## After

![image](https://user-images.githubusercontent.com/677704/49688629-5db79f00-fb15-11e8-9cd3-e6afa8e07b64.png)

<details>
<summary>Original text by @Mpdreamz</summary>
Currently exceptions bubble out of `RunTargets(Async)()`

```cmd
C:\Projects\elastic\net-master>build.cmd walkdog
Bullseye: Starting... (walkdog)
Bullseye/walkdog: Starting...
Bullseye/walkdog: Failed! boom! (8.34 ms)
Bullseye: Failed! (walkdog) (23.4 ms)

Unhandled Exception: System.Exception: boom!
   at targets.WalkDogTarget.Exec() in C:\Projects\elastic\net-master\build\targets\Progra
m.cs:line 40
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, Co
ntextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Bullseye.Internal.ActionTarget.RunAsync(Boolean dryRun, Boolean parallel, Logger lo
g) in C:\projects\bullseye\Bullseye\Internal\ActionTarget.cs:line 25
   at Bullseye.Internal.ActionTarget.RunAsync(Boolean dryRun, Boolean parallel, Logger lo
g) in C:\projects\bullseye\Bullseye\Internal\ActionTarget.cs:line 31
   at Bullseye.Internal.TargetCollection.RunAsync(String name, List`1 explicitTargets, Bo
olean skipDependencies, Boolean dryRun, Boolean parallel, ConcurrentDictionary`2 targetsR
an, Logger log, Stack`1 targets) in C:\projects\bullseye\Bullseye\Internal\TargetCollecti
on.cs:line 83
   at Bullseye.Internal.TargetCollection.RunAsync(List`1 names, Boolean skipDependencies,
 Boolean dryRun, Boolean parallel, Logger log) in C:\projects\bullseye\Bullseye\Internal\
TargetCollection.cs:line 38
   at Bullseye.Internal.TargetCollection.RunAsync(List`1 names, Boolean skipDependencies,
 Boolean dryRun, Boolean parallel, Logger log) in C:\projects\bullseye\Bullseye\Internal\
TargetCollection.cs:line 47
   at Bullseye.Internal.TargetCollectionExtensions.RunAsync(TargetCollection targets, Lis
t`1 args, IConsole console) in C:\projects\bullseye\Bullseye\Internal\TargetCollectionExt
ensions.cs:line 171
   at targets.Program.Main(String[] args) in C:\Projects\elastic\net-master\build\targets
\Program.cs:line 26
   at targets.Program.<Main>(String[] args)

C:\Projects\elastic\net-master>
```

If the order were different:

```cmd
C:\Projects\elastic\net-master>build.cmd walkdog
Bullseye: Starting... (walkdog)
Bullseye/walkdog: Starting...

Unhandled Exception: System.Exception: boom!
   at targets.WalkDogTarget.Exec() in C:\Projects\elastic\net-master\build\targets\Progra
m.cs:line 40
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, Co
ntextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Bullseye.Internal.ActionTarget.RunAsync(Boolean dryRun, Boolean parallel, Logger lo
g) in C:\projects\bullseye\Bullseye\Internal\ActionTarget.cs:line 25
   at Bullseye.Internal.ActionTarget.RunAsync(Boolean dryRun, Boolean parallel, Logger lo
g) in C:\projects\bullseye\Bullseye\Internal\ActionTarget.cs:line 31
   at Bullseye.Internal.TargetCollection.RunAsync(String name, List`1 explicitTargets, Bo
olean skipDependencies, Boolean dryRun, Boolean parallel, ConcurrentDictionary`2 targetsR
an, Logger log, Stack`1 targets) in C:\projects\bullseye\Bullseye\Internal\TargetCollecti
on.cs:line 83
   at Bullseye.Internal.TargetCollection.RunAsync(List`1 names, Boolean skipDependencies,
 Boolean dryRun, Boolean parallel, Logger log) in C:\projects\bullseye\Bullseye\Internal\
TargetCollection.cs:line 38
   at Bullseye.Internal.TargetCollection.RunAsync(List`1 names, Boolean skipDependencies,
 Boolean dryRun, Boolean parallel, Logger log) in C:\projects\bullseye\Bullseye\Internal\
TargetCollection.cs:line 47
   at Bullseye.Internal.TargetCollectionExtensions.RunAsync(TargetCollection targets, Lis
t`1 args, IConsole console) in C:\projects\bullseye\Bullseye\Internal\TargetCollectionExt
ensions.cs:line 171
   at targets.Program.Main(String[] args) in C:\Projects\elastic\net-master\build\targets
\Program.cs:line 26
   at targets.Program.<Main>(String[] args)

Bullseye/walkdog: Failed! boom! (8.34 ms)
Bullseye: Failed! (walkdog) (23.4 ms)


C:\Projects\elastic\net-master>
```

The last lines would always indicate the faulty target and a user does not have to scroll their terminal.

</details>

**Comment by adamralph** [comment]
@Mpdreamz ultimately, I have to throw an exception, so even if I print out the exception in the intermediate output, it's up the host console app to deal with the unhandled exception, which by default will print it all out again.

**Comment by Mpdreamz** [comment]
It could be exposed as `TargetExceptionHandler(Func<Exception, bool>)` prior to `RunTargets()`. This would allow me to control what happens.

**Comment by adamralph** [comment]
I guess something like that could work. I'll keep thinking about it...

**Comment by adamralph** [comment]
@Mpdreamz I started looking into this, but the implementation starts to get quite involved. If the delegate returns `true` (i.e. the exception has been handled) then I need an alternate error-code style return from the method which invokes the target delegate, and that is viral, since it needs to be passed up the whole call stack, and each consumer that currently rethrows the exception needs to handle both the exception based model and the error-code model.

Similarly to https://github.com/adamralph/bullseye/issues/163 I'm not sure that the benefit of a bit less scrolling is worth the cost of the added complexity. And even in the scenario you propose, there will still be _some_ scrolling to get to the exception message.

Thoughts?

**Comment by Mpdreamz** [comment]
Currently the only way to fail a target is to throw an exception in it. There are often cases where I don't want a full stack trace as the failure message is descriptive enough and a stack trace only adds noise.

Ideally that message occurs after any console out from the task as now we read the occurrence of events in natural order. With the target executor finishing with a summary of what transpired. This is something I am accustomed too from other runners (gradle/fake/cake/etc).

I did a quick spike to explore a non viral route:

https://github.com/Mpdreamz/bullseye/commit/92fd83185a2189b22ab62a548d6f7051c0ae1bfd

![image](https://user-images.githubusercontent.com/245275/49145436-10ab2000-f300-11e8-93f7-d5b229a84a2c.png)

I realize I might not have a full picture of all the places `Bullseye` might end up being used and how this would bite those usecases 😄

**Comment by Mpdreamz** [comment]
Maybe what I want is a way to print a summary more then anything else:

e.g from a FAKE build script:

```
---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target                    Duration
------                    --------
Clean                     00:00:01.5973051
ChangeVersion             00:00:00.0216123
Version                   00:00:00.0449321
Restore                   00:00:02.5392854
FullBuild                 00:00:06.7928622
Test                      00:00:26.2444011
InternalizeDependencies   00:00:08.4346894
Build                     00:00:00.0017516
Release                   00:00:04.1651395
Total:                    00:00:49.9985537
---------------------------------------------------------------------
Status:                   Ok
---------------------------------------------------------------------
```

I really like having this be the last thing printed consistently as I often keep an eye out on task running times.

**Comment by adamralph** [comment]
@Mpdreamz the problem with your spike is that the process returns 0, so the CI system will think the build has passed.

> Maybe what I want is a way to print a summary more then anything else

That's a fair call, and it's something I've had in the back of my mind for a while. Would you like to raise a new issue specifically for that?

**Comment by Mpdreamz** [comment]
> @Mpdreamz the problem with your spike is that the process returns 0, so the CI system will think the build has passed.

Yeah this becomes the responsibility of the caller, just as when putting a try catch around `RunTargets` to prevent a full stacktrace on the command line in certain cases.

**Comment by adamralph** [comment]
Great thanks! If we add a summary is there still a need for the exception intercepting described here?

**Comment by adamralph** [comment]
@Mpdreamz FYI https://github.com/adamralph/bullseye/issues/172 will allow Bullseye to intercept the exceptions internally and write them out within the target, just as you are proposing here.

**Comment by Mpdreamz** [comment]
Thank you @adamralph 

I currently have this: https://github.com/elastic/elasticsearch-net/blob/spike/bullseye/build/targets/Program.cs#L28-L36

but I much rather use the exit method without a try catch in my build script. Also the delay as noted on the PR is very real and annoying 😄

**Comment by adamralph** [comment]
@Mpdreamz have to you tried [beta 3](https://www.nuget.org/packages/Bullseye/2.3.0-beta.3) yet, with `RunTargetsAndExitAsync`?

**Comment by Mpdreamz** [comment]
No, won't have time to continue porting my build to bullseye this week sadly.

**Comment by adamralph** [comment]
Released in [beta 6](https://www.nuget.org/packages/Bullseye/2.3.0-beta.6).
