### ISSUE TITLE
Custom Logger

### ISSUE THREAD

**Issue by Mpdreamz** [adamralph/bullseye#163]
Relates to #162 and maybe even #95 

Are there any plans to open up the Logger: https://github.com/Mpdreamz/bullseye/blob/master/Bullseye/Internal/Logger.cs#L12

More wondering out of my obsessive need to tinker rather than a real use case. In this case I would love to control how the tasks get ouput using something fancier then `/` to separate the chain.

If exceptions would flow to the logger in the future (#162) I would love to provide diagnosers for known exceptions though.

**Comment by adamralph** [comment]
@Mpdreamz use case or GTFO. 😉 

But seriously, I'd rather not spend time on something until there is a use case.

**Comment by adamralph** [comment]
> something fancier then / to separate the chain

If you have a great idea for that, I'd entertain the possibility of changing it in Bullseye.

**Comment by Mpdreamz** [comment]
>@Mpdreamz use case or GTFO.

😹 totally agree. 

One other usecase that came to mind was to use TeamCity service messages for Task start/end to report build progress.

https://confluence.jetbrains.com/display/TCD9/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingMessagesForBuildLog

But this could either be supported OOTB or not at all for all I care TBH as I am moving most my infra off of TC atm so have no **real** need for it.

**Comment by Mpdreamz** [comment]
> If you have a great idea for that, I'd entertain the possibility of changing it in Bullseye.

Great will need [emoji support](https://github.com/Microsoft/console/issues/190) but this is what I sort of wanted.

```
Bullseye  : Starting... (default)
Bullseye -> maketea: Starting...
Tea made
Bullseye <- maketea: Succeeded. (7.63 ms)
Bullseye -> drinktea: Starting...
Ahh... lovely!
Bullseye <- drinktea: Succeeded. (<1 ms)
Bullseye -> gitstatus: Starting...

Bullseye <- gitstatus: Succeeded. (152 ms)
Bullseye <- default: Succeeded.
Bullseye  : Succeeded. (default) (178 ms)
```

I also would like to control the `Bullseye` moniker. In some cases our repos are build as part of a very big multiple repository build script and it would help distinguish the origin at a quick glance.

**Comment by adamralph** [comment]
@Mpdreamz I gave the arrows a try, but I can't say I'm hugely convinced. Personally I find the "back and forth" quite distracting:

<img src="https://user-images.githubusercontent.com/677704/49104013-288d9000-f27d-11e8-9fea-6ad9ba6f9cbc.png" width="347px" />

Regarding controlling the message prefix, I'm not sure it will really buy you much. Consider:

```
FooSolution/build: Starting...
.
.
.
(large amount of output from dotnet build)
.
.
.
FooSolution/build: Succeeded
FooSolution/test: Starting...
.
.
.
(large amount of output from dotnet test)
.
.
.
FooSolution/test: Succeeded
```

vs

```
=== FooSolution start ===    // your own log message
Bullseye/build: Starting...
.
.
.
(large amount of output from dotnet build)
.
.
.
Bullseye/build: Succeeded.
Bullseye/test: Starting...
.
.
.
(large amount of output from dotnet test)
.
.
.
Bullseye/test: Succeeded.
=== FooSolution end ===    // your own log message
```

Sure, you get "FooSolution" a little more often, but you're going to have to do some scrolling in both cases. I'm not sure the benefit of less scrolling is worth the cost of the added complexity in the Bullseye API.

What do you think?

**Comment by Mpdreamz** [comment]
> Personally I find the "back and forth" quite distracting

I agree, thank you for exploring this 👍 

> I'm not sure the benefit of less scrolling is worth the cost of the added complexity in the Bullseye API

It's definitely something I can let go of at this stage, will reopen if it becomes something I run into often.
