### ISSUE TITLE
Summary reporting

### ISSUE THREAD

**Issue by Mpdreamz** [adamralph/bullseye#168]
What I want is a way to print a summary as the very last thing on the command line

e.g from a FAKE build script:

```
---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target                    Duration
------                    --------
Clean                     00:00:01.5973051
ChangeVersion             00:00:00.0216123
Version                   00:00:00.0449321
Restore                   00:00:02.5392854
FullBuild                 00:00:06.7928622
Test                      00:00:26.2444011
InternalizeDependencies   00:00:08.4346894
Build                     00:00:00.0017516
Release                   00:00:04.1651395
Total:                    00:00:49.9985537
---------------------------------------------------------------------
Status:                   Ok
---------------------------------------------------------------------
```

I really like having this be the last thing printed consistently as I often keep an eye out on task running times.

**Comment by adamralph** [comment]
@Mpdreamz how does this look?

<img src="https://user-images.githubusercontent.com/677704/53685437-95984200-3d12-11e9-9160-5cdd95fae83c.png" width="429px" />

**Comment by Mpdreamz** [comment]
Awesome!

Nitpick prefer left over center align in the header personally.

A total row would be nice as well. 

Thanks for picking this up!

**Comment by adamralph** [comment]
Thanks for the feedback @Mpdreamz. How about this?

<img src="https://user-images.githubusercontent.com/677704/54084340-ad358300-432f-11e9-9951-52006a90441f.png" width="423px" />

It feels a bit weird to have "Failed"/"Succeeded" next to "Total", but I'm yet to think of something better. I thought about "All" instead of "Total", but that doesn't feel great either.

**Comment by adamralph** [comment]
I just realised there's a problem in the failure timings: the time shown in the summary is only the time taken to execute the target with respect to the last input value (e.g. `fail/20`) rather than the entire target (e.g. `fail`).

I'm also considering whether the summary should show the time taken to run the target for each input value seperately.

**Comment by Mpdreamz** [comment]
Unformed thought, spit balling here:

````
Target            Duration
-----------       -----------------
✓ T1             (00:00:00:0027148)
├─ ✓ T1: a        00:00:00.0003131
└─ ⨯ T1: b        00:00:00.0024017  
✓ T2              00:00:00:0067148
├─ ✓ T3           00:00:00.0003131
└─ ⨯ T4           00:00:00.0024017
-------------------------------------
                   00:00:00.0024017
````

The first visualing inputs (with total time) and the latter parallel tasks dependent on T2

Also duration being pretty printed right aligned might look nice too


````
Target            Duration
-----------       ---------
✓ T1                12.2  s
├─ ✓ T1: a             2 ms
└─ ⨯ T1: b            12  s 
---------------------------
                     12.2 s
````

**Comment by blairconrad** [comment]
> The duration pretty printing in the summary could get tricky since the durations printed during the run graduate through `<1 ms`, `X ms`, `X s`, `X min`, and `X min Y s`. I'm not sure if a mix of all those could be nicely aligned in a column, but I'm happy to experiment.

Me, I'm happy with the long format you have, but if you want to have pretty numbers and align, I have a question.
Why  "min" and "s"? Why not "m" and "s" or "min" and "sec"? I partly ask because having "m" and "s" will compact the result a little. (And partly because I like patterns….)


```

**Comment by adamralph** [comment]
@blairconrad good question, and I don't have a good answer. I think I may have been imitating the output from some other tool, but which one I don't know. Or perhaps I subconciously wanted to distinguish between "month" and "minute". Or perhaps I'm now getting inventive with excuses.

Anyhow, I've raised https://github.com/adamralph/bullseye/issues/225. Thanks for pointing this out.

**Comment by blairconrad** [comment]
Thank you. But now I'm worried that I won't know whether my build took a minute a month. 😟

**Comment by adamralph** [comment]
@Mpdreamz @blairconrad please see the screen shots below, demonstrating the latest output.

Some things to note:

- For targets with inputs, the time to execute the target for each input is shown, as well as the total time for the target.
- The times are pretty printed, with three fixed decimal places for consistency.
- The warning for targets with parameters but no inputs is repeated in the summary.
- I've removed the total row, since was a repetition of what's already in the last log line.

This first screen shot is the output from the smoke test project, which demonstrates all the possibilities. The second is from a simple consuming project (LiteGuard) and the third is from a more complex consuming project (FakeItEasy).

<img src="https://user-images.githubusercontent.com/677704/58749945-55209f80-848c-11e9-9119-378955c388b7.png" width="624px" />

![image](https://user-images.githubusercontent.com/677704/58750117-68346f00-848e-11e9-8beb-f6e92bf8c4a4.png)

![image](https://user-images.githubusercontent.com/677704/58750131-92862c80-848e-11e9-8475-3a3b6cb2e645.png)

**Comment by Mpdreamz** [comment]
So awesome, love it!

I would prefer `duration/result/target` since the first two are fixed width and therefore always visually close to the target information.

**Comment by adamralph** [comment]
@Mpdreamz here are the same screenshots with your proposed column order. What do you think?

In fact, none of the columns are fixed width. They all dynamically size to fit the content. But yes, Duration will never get very wide, and Outcome will never be wider than 10 chars.

<img src="https://user-images.githubusercontent.com/677704/58761421-8ceb1e00-8544-11e9-8a65-a16ccc2a742e.png" width="444px" />

<img src="https://user-images.githubusercontent.com/677704/58761443-b73cdb80-8544-11e9-8ccf-a5cd06b7d8d2.png" width="436px" />

<img src="https://user-images.githubusercontent.com/677704/58761497-54980f80-8545-11e9-9020-eda8aefb74a8.png" width="907px" />

**Comment by adamralph** [comment]
And here's a slight twist, also showing the duration as a percentage of the total, which is probably more useful than the absolute time.

<img src="https://user-images.githubusercontent.com/677704/58762173-96c54f00-854d-11e9-909f-5e917a859a7f.png" width="959px" />

**Comment by adamralph** [comment]
And another formatting tweak to limit timings in seconds and milliseconds to two and zero decimal digits respectively.

<img src="https://user-images.githubusercontent.com/677704/58762391-ef95e700-854f-11e9-9c69-7735e60deeae.png" width="938px" />

**Comment by blairconrad** [comment]
Hey, @adamralph. Unsolicited feedback: I think the columns look really slick. Easy to read _and_ pretty!

One minor point (and maybe not a big deal) is that while the tree structure on the absolute times really aids understanding, I find the flat list of percentages is a little off-putting, as the numbers feel like they're all on the same footing, so I'm expecting them to sum to 100%…

**Comment by adamralph** [comment]
@blairconrad your feedback is always welcome! And I did, in fact, solicit it back [here](https://github.com/adamralph/bullseye/issues/168#issuecomment-497951698). 🙂

How about this?

<img src="https://user-images.githubusercontent.com/677704/58764120-e282f300-8563-11e9-981b-782432c44185.png" width="952px" />

**Comment by adamralph** [comment]
_Side note: my OCD is currently wallowing in the fact that the total time of that last example build was exactly 100 seconds, so the percentage numbers match the timings._ 😻

**Comment by blairconrad** [comment]
Oh, so you did! I had a weird day yesterday and completely missed the `@`. I like it. Worth the extra 2 characters of width, IMO. Thanks!

**Comment by Mpdreamz** [comment]
So good! Looking forward to seeing this on my terminal :)

**Comment by adamralph** [comment]
Unfortunately Appveyor Windows jobs don't render the higher unicode characters so I've had to try and fudge it with characters in the ascii range. Right now I can't think of anything better than this:

![image](https://user-images.githubusercontent.com/677704/59930923-1f942400-9444-11e9-889c-f10df5984a40.png)

@blairconrad @Mpdreamz what do you think? Is it acceptable enough?

**Comment by blairconrad** [comment]
@adamralph, I think it's acceptable, but it's too bad you can't use code page 437.

**Comment by adamralph** [comment]
FWIW, I've raised https://github.com/appveyor/ci/issues/2993, but I won't wait for it before releasing this feature.

**Comment by adamralph** [comment]
I'm also wondering whether it would be better to omit the vertical elements:

![image](https://user-images.githubusercontent.com/677704/59966671-f1841200-951f-11e9-8d38-34cd171f5824.png)

Or even omit the symbols entirely:

![image](https://user-images.githubusercontent.com/677704/59966706-87b83800-9520-11e9-8ea0-38c4d840c4f7.png)

**Comment by blairconrad** [comment]
Interesting alternatives, @adamralph. Me, I think omitting the symbols looks best. I was initially confused by the rogue hyphens.

**Comment by adamralph** [comment]
Thanks @blairconrad. I'm in agreement with your ranking.
