### ISSUE TITLE
[Question] Debugging Bullseye project

### ISSUE THREAD

**Issue by bdelsaz** [adamralph/bullseye#224]
This is not an issue, but a question.
I have created a console project in dotnet core 2.2 to build a bunch of projects. As per the documentation and examples, I use

```
            Target("default", DependsOn(_targetNames.ToArray()));
            RunTargetsAndExit(args);
```
When debugging in my IDE (visual studio in this case) the command line window disappears too fast to see the errors or the reporting on each task. This is expected behaviour of RunTargetsAndExit. However, how can I prevent the commandline window to close so that I can see all the errors?

Thank you in advance for the help and for creating this useful tool.

**Comment by bdelsaz** [comment]
@adamralph  thanks for the response! unfortunately the solution you proposed (third option) dit not work for me. The program exited just as with `RunTargetsAndExit.` 

So to view the results I need to build the BullsEye project using dotnet build & dotnet run in an external console. Not a big deal, just wanted to make sure I was not missing anything.

Thanks again!

**Comment by adamralph** [comment]
@bdelsaz it's strange that it doesn't work for you.

Can you please try this isolated example? https://github.com/adamralph/bullseye-debugging

Note that I also added `Console.WriteLine("Press any key to exit.");` to make it obvious what is happening.

**Comment by bdelsaz** [comment]
Well I must have done something wrong the first time, because this time it does work :embarrassed:
I run your example and it works perfectly.

So in conclussion, adding `AppDomain.CurrentDomain.ProcessExit += (s, e) => Console.ReadKey(); `right at the beginning of the Main() does the trick.

Thank you for putting the example together!

**Comment by adamralph** [comment]
That's great to hear @bdelsaz! I'll get this into an FAQ ASAP. Thanks again for raising the question.
