### ISSUE TITLE
Provide an alternative to Environment.Exit

### ISSUE THREAD

**Issue by ejball** [adamralph/bullseye#226]
Calling `Environment.Exit` from `RunTargetsAndExit` prevents us from doing anything after we run the targets.

Could `RunTargets` (or some other method like `RunTargetsAndReturn`) do the same thing as `RunTargetsAndExit`, except return the exit code that should be returned from `Main`, instead of calling `Environment.Exit`?

**Comment by adamralph** [comment]
Hey @ejball, thanks for asking this question.

The current `RunTargets` (which is marked as obsolete) effectively does what you want, since it allows exceptions to walk up the stack. From there, you can catch the exception and decide what to do. E.g. return a non-zero exit code.

Out of interest, what is the use case for more statements after `RunTargetsAndExit()`? If there is a valid use case, I'm willing to remove the obsolete attribute.

**Comment by ejball** [comment]
Thanks for the quick response! To be honest, I mostly just find it unsettling. I'm calling `RunTargetsAndExit` from a delegate passed to `CommandLineApplication.OnExecute` of `McMaster.Extensions.CommandLineUtils`, which accepts an exit code. I don't know if that code does anything interesting after it calls `OnExecute`, but if there are `using` statements, `Dispose` won't be called, etc.

It makes sense to make `RunTargetsAndExit` the most prominent method to help users fall into the "pit of success", but I'm just hoping for some way to use it without force-quitting the app.

**Comment by adamralph** [comment]
@ejball I guess the disposal of managed resources (via either a `using` block or an explicit `finally`) could be considered a valid use case for code which runs after running the targets. Most of the time I'd expect that to be done _within_ a target, but I guess there could be edge cases where something expensive to setup/teardown would be better shared across targets.

I have several partially formed thoughts about this floating around my head. I'll put ~pen to paper~ hand to keyboard again when they are more coherent.

In the meantime, I suggest you use `RunTargets` and ignore the obsolete method warnings. You can either catch an exception and transform it to an exit code for `McMaster.Extensions.CommandLineUtils` or you can just allow `McMaster.Extensions.CommandLineUtils` to handle it, safe in the knowledge that it has the ability perform any necessary disposals.

**Comment by ejball** [comment]
Thanks; that makes good sense. I'll switch to `RunTargets` and ignore the warning.

**Comment by adamralph** [comment]
Thanks again for raising this @ejball. The methods in question will be renamed in https://github.com/adamralph/bullseye/issues/232.
