### ISSUE TITLE
Targets not build if name is not default and with custom arguments

### ISSUE THREAD

**Issue by unuunc** [adamralph/bullseye#227]
1. Using following gist published 
https://gist.github.com/adamralph/d6a3167c8fe0d4e24721d8d2b9c02989
2. Just change the name of default target to something else (say default1 )
3. run following 
dotnet run -- default1  --foo=bar

Expected : I was expecting it to execute default1 target 

Actual : "Bullseye: Unknown option --foo=bar. "--help" for usage."

Same can be tried without changing name , just specify target name , say default it will throw same error.

**Comment by adamralph** [comment]
@unuunc thanks for raising this. I guess that McMaster.Extensions.CommandLineUtils doesn't allow the target names to fall through into `CommandLineApplication.RemainingArguments`. 😞

**Comment by adamralph** [comment]
@unuunc I've updated the gist to fix it: https://gist.github.com/adamralph/d6a3167c8fe0d4e24721d8d2b9c02989

**Comment by unuunc** [comment]
thanks
