### ISSUE TITLE
Make target names case insensitive

### ISSUE THREAD

**Issue by Mpdreamz** [adamralph/bullseye#230]
Right now target is case sensitive, it would be nice if this was case insensitive allowing you to use nameof(Method) but pass `method` on the command line

**Comment by adamralph** [comment]
Hey @Mpdreamz thanks for raising this. I'm on the road right now but I'll look into this ASAP.

**Comment by adamralph** [comment]
@Mpdreamz I've converted this to a breaking feature, since I can't think of any good reason not to do it, but it will have to wait for a major release. That said, there are a number of breaking features in the backlog now, so perhaps it's time to do it.

**Comment by adamralph** [comment]
Released in [3.0.0-alpha.1](https://www.nuget.org/packages/Bullseye/3.0.0-alpha.1).

@Mpdreamz @ygel perhaps you'd like to try it out?

**Comment by ygel** [comment]
Certainly!
