### ISSUE TITLE
Support for known exceptions that don't report their full stacktrace

### ISSUE THREAD

**Issue by Mpdreamz** [adamralph/bullseye#231]
Bare with me @adamralph I am just throwing tickets at you without fully knowing what I want 😸 

Here I am running .NET tests by calling `dotnet test` through https://github.com/nullean/proc which throws an exception on an unknown exitCode (defaulting to anything not `0`).

The result is a bit noisy:

![image](https://user-images.githubusercontent.com/245275/55263190-7a1c4a80-5270-11e9-8538-bce4cb9cac2a.png)

I am only interested in the first stracktrace from the failing tests.

It would be nice if I could mark `ProcExecException` somehow to only display the `ex.Message`.

**Comment by Mpdreamz** [comment]
Another way to do this would be to explicitly support `Targets.Fail("message")` which would mark the current;y running task as failed. Would work for non exception cases too e.g validation failures.

**Comment by adamralph** [comment]
Hey @Mpdreamz, you should be able to do this today:

```c#
RunTargetsAndExit(args, messageOnly: ex => ex is ProcExecException);
```

**Comment by adamralph** [comment]
I see [this is working for you](https://github.com/elastic/elasticsearch-net/blob/eee172b09f85dfe610f89f8ae1d401a66b338ca8/build/scripts/Targets.fs#L84) so I'm closing this. 🙂
