### ISSUE TITLE
Bullseye build log messages showing hex code for slash in Azure Pipelines CI

### ISSUE THREAD

**Issue by mysticmind** [adamralph/bullseye#243]
![image](https://user-images.githubusercontent.com/2864208/58749190-55c33100-84a0-11e9-9539-3b7d4ddfff78.png)

https://dev.azure.com/jasperfx-marten/marten/_build/results?buildId=2 - You could open up the build step in any of the jobs and see the same as an example.

**Comment by adamralph** [comment]
Hi @mysticmind, thanks for raising this. This is a bug that was _knowningly introduced_ in [Azure Pipelines](https://github.com/microsoft/azure-pipelines-agent/issues/1569).

As you can see, other people have the same problem with relation to other tools which use ANSI colouring:

- https://github.com/microsoft/azure-pipelines-agent/issues/2140
- https://github.com/Homebrew/homebrew-test-bot/pull/250

I suggest you follow up on this over at https://github.com/microsoft/azure-pipelines-agent

In the meantime, you could choose to temporarily switch off coloured output from bullseye with the `--no-color` option.

**Comment by mysticmind** [comment]
@adamralph Thanks for the heads up. I will follow up on the Azure Pipelines repo.
