### ISSUE TITLE
Emit TeamCity blockOpened and blockClosed messages

### ISSUE THREAD

**Issue by adamralph** [adamralph/bullseye#248]
_Replaces #218._

When targets are starting:

```c#
$"##teamcity[blockOpened name='{targetName}']"
```

and finishing:

```c#
$"##teamcity[blockClosed name='{targetName}']"
```

**Comment by damianh** [comment]
Lovely!

Oh wait, I don't use TeamCity anymore :P

**Comment by adamralph** [comment]
Hah! OK, then I'll close. We can revisit if/when someone wants it.

**Comment by damianh** [comment]
Fair enough.
