### ISSUE TITLE
An API which looks better when `using static`

### ISSUE THREAD

**Issue by adamralph** [adamralph/bullseye#34]
[Feedback](https://github.com/FakeItEasy/FakeItEasy/pull/1375#discussion_r197657657) from @blairconrad and @thomaslevesque was that `Add()` and `Run()` are too general in their bare forms when `using static`. An alternative is `AddTargets()` and `RunTargets()`, although that is a little verbose when you consider `Targets.AddTarget()`, `Targets.RunTargets()`. Ideally it would be great to have an API which looks great in both scenarios although I'm not sure that's possible.

This would include a deprecation of the previous methods, and their removal in 2.0.

**Comment by blairconrad** [comment]
If you don't mind having more than one way to do it, you could keep `Add` and `Run` and add a class solely to support the `AddTargets` and friends.

```c#
public static class VerboseTargets // okay, that could use some work
{
	public static string[] DependsOn(params string[] dependencies) …

    public static void AddTarget(string name, IEnumerable<string> dependsOn, Func<Task> action) …

    public static void RunTargets(IEnumerable<string> args)action) …
}
```

For that matter, that's what I could've done over in SelfInitializingFakes.

**Comment by adamralph** [comment]
I prefer to have one way of doing things where possible, but yes, it's an option.

**Comment by blairconrad** [comment]
Okay, it's agreed. The one way to do it is just `using static` the verbose methods. Rename all the methods to be a little chattier (except `DependsOn`) Change all the samples to show the `using static`, and you're done. Good chat!

:stuck_out_tongue_winking_eye: 

But seriously, I'd give it some thought.

**Comment by adamralph** [comment]
That probably makes sense. Once the methods look good on their own, there should never be a need to qualify them with the type name. Unless of course some other type has the same method signature, but that's moving into vanishingly sharp corner case territory.

**Comment by adamralph** [comment]
@blairconrad @thomaslevesque what do you think about `Target()` instead of `Add()`? This follows the example of [Fake](https://fake.build/legacy-gettingstarted.html#The-build-script).

**Comment by thomaslevesque** [comment]
I like it. It reads better, e.g. `Target("foo", DependsOn("bar"))` reads like "target foo depends on bar", which is nice.

**Comment by thomaslevesque** [comment]
> Not quite as nice to read when there's no `DependsOn`:

What about this?

```csharp
Target("testsDirectory", Does(() => Directory.CreateDirectory(testsDirectory)));
```

Maybe too verbose...

**Comment by blairconrad** [comment]
Where `Does` is a do-nothing method, not unlike `DependsOn`?
It could then be omitted by people who don't care for it. (Or alternatively, added by the yahoos that want extra syntax.)

It reads okay, but sort of in my head `=>` reads as "does" or "takes nothing and does".

So... it reads nice, but I'm not sure it brings enough value to warrant including it?

**Comment by thomaslevesque** [comment]
> So... it reads nice, but I'm not sure it brings enough value to warrant including it?

Probably not

**Comment by adamralph** [comment]
I'm not convinced it's worth adding a no-op `Does()`. I wonder whether I should ever have added `DependsOn()`. Ultimately, the only reason I did is to make up for the lack of a terse array initializer in C#. 

As it stands, the most terse way of adding a target without `DependsOn()` is:

```c#
Target("foo", new[] { "bar" }, () => ...);
```

The "standard" way to add some readability is to add the param name:

```c#
Target("foo", dependsOn: new[] { "bar" }, () => ...);
```

But I still hate that array initializer, which is why I introduced `DependsOn()` (included for completeness):

```c#
Target("foo", DependsOn("bar"), () => ...);
```

If we had a better initializer, I'd be happy to drop `DependsOn()`:

```c#
Target("foo", dependsOn: {"bar"}, () => ...);
Target("foo", dependsOn: ["bar"], () => ...);
// etc.
```

BTW: there's a [new no-op `ForEach()` coming in 1.1](https://github.com/adamralph/bullseye/pull/36), so if I'm going to rip out the no-ops, 1.1 would be the time to do it.`

**Comment by blairconrad** [comment]
I like `DependsOn`. It's a clear indicator of what the parameter is doing. And as you say, it's much more attractive than the array initializer.

The value is there. Far more than for `Does`.

I'd be tempted to go the other way and strengthen it: make `Target` take an enumerable of `Dependency` or similar, instead of of strings, with `DependsOn` upconverting from string. It's a little bit of extra wiring or conversion, but might reduce the chance of misuse. A teeny bit.

**Comment by adamralph** [comment]
Thanks @blairconrad. I'll give that some thought too.
