### ISSUE TITLE
Continue on error/exception

### ISSUE THREAD

**Issue by damianh** [adamralph/bullseye#373]
## Use case(s)

It is desirable to run all test projects as individual targets and not stop on the first time NonZeroExitCodeException, skipping the remaining test projects.

## Description

Using simple-exec to run `dotnet test {project}` will return a `NonZeroException` if any test fails.

However I have multiple test projects each run as individual targets. I want to record that they failed but I don't (necessarily) want bullseye to stop. I would like the fact that the target has failed to be recorded, processing to continue and then build "fails" at the end.

## Alternatives

Capture the `NonZeroExitCodeException` and flip a staic flag `oneOrMoreTestsFailed`:
![image](https://user-images.githubusercontent.com/57436/68214909-99d1d900-ffde-11e9-88c9-d8ffab61e8af.png)

Problem 1 with this: the individual targets say "succeeded" when it is desirable they should say `failed!`:
![image](https://user-images.githubusercontent.com/57436/68215130-00ef8d80-ffdf-11e9-9ce8-819dba8a6620.png)

Problem 2: doesn't work when running specific target `test`
![image](https://user-images.githubusercontent.com/57436/68215368-66dc1500-ffdf-11e9-924c-e3b1351b1196.png)

**Comment by damianh** [comment]
Just noticed from the summary that targts are in reverse order (red arrow) but their input collections are correct order (green arrow)

![image](https://user-images.githubusercontent.com/57436/68215603-d225e700-ffdf-11e9-9930-0030be293cf5.png)

**Comment by damianh** [comment]
A suggestion...

Extend `Target` signature with an OnError flag indicating how processing should continue

	public enum OnError
	{
     	StopImmediately,  // default
        StopAfterTargetCompleted, // runs all the input collection before stopping.
        ContinueAndFailAtEnd, // continues processing but fails at the end
        ContinueAndIgnore, // continues processing and does not fail at end
    }

	public static void Target<TInput>(
		string name,
		IEnumerable<string> dependsOn,
		IEnumerable<TInput> forEach, Func<TInput, Task> action
		OnError onError)

**Comment by adamralph** [comment]
Thanks for raising this @damianh. I'll have a closer look ASAP.

**Comment by adamralph** [comment]
@damianh I can see the use case for this. Do you have any idea how you'd like the public API to look?

Perhaps something like this?

```c#
Target<TInput>(
    string name,
    IEnumerable<string> dependsOn,
    IEnumerable<TInput> forEach,
    Func<Exception, bool> continueOnException,    // new
    Action<TInput> action)
```

E.g. as a blunt instrument, you'd just supply `_ => true` for the new parameter.

**Comment by damianh** [comment]
This issue with that is that all I can do is fail now or not at all. I might want fail at end of all targets or fail at end of iteration of the `forEach`.

I also understand this makes the api more complex, away from from the desired simplicity.

**Comment by adamralph** [comment]
@damianh I think I see what you mean. Although I'm not sure failing at the end of all targets would ever make sense. I could see a use case for failing at the end of all _dependencies_ though. That is, for the current target, run all the dependencies first (as usual) but continue with the next dependency when one fails. That would enable the following:

```c#
Target("test", DependsOn("test-1", "test-2"), runNextDependencyOnException: _ => true);
```

So putting it all together:

```c#
Target<TInput>(
    string name,
    IEnumerable<string> dependsOn,
    IEnumerable<TInput> forEach,
    Func<Exception, bool> runNextDependencyOnException,    // new
    Func<Exception, bool> runNextInputOnException,    // new
    Action<TInput> action)
```

> I also understand this makes the api more complex, away from from the desired simplicity.

Yep, that's my main concern right now. I'm fine with the use cases and functionality, but the challenge is how to get this into the API without making it too complex regarding both usability and maintainability.

The `Target` method is already heavily overloaded and difficult to maintain. It could be time to switch to optional parameters, but that comes with other costs. I need to give it some more thought. Any ideas would be welcome.

**Comment by damianh** [comment]
Is this viable? 🤔

```
Target<TInput>(
    string name,
    IEnumerable<string> dependsOn,
    IEnumerable<TInput> forEach,
    Func<TException, bool> runNextDependencyOnException,    // new
    Func<TException, bool> runNextInputOnException,    // new
    Action<TInput> action) where TException: Exception
```

**Comment by damianh** [comment]
There are number of use cases to fail a build outside of exceptions on any give target https://www.jetbrains.com/help/teamcity/build-failure-conditions.html. In my case I still want my packaging steps to fail 

Now I'm totally questioning the exception based control of flow here. I think I want to be more in charge of that... hmmm 🤔

**Comment by adamralph** [comment]
> There are number of use cases to fail a build outside of exceptions on any give target.

Sure, but that's venturing outside the use case presented in this issue. For the problem shown with your `test` target, `runNextInputOnException` should be all you need.

Do you have a different use case?

**Comment by adamralph** [comment]
OK, I guess you might still want other things to run, such as `publish`, but that would be controlled using `runNextDependencyOnException` when defining the target that depends on them, which I guess is `default`. So:

```c#
...
Target(Test, DependsOn(Build), runNextInputOnException: _ => true, ...);
...
Target("default", DependsOn(Test, Publish), runNextDependencyOnException: _ => true);
```

I.e. you would never want a target to run if one of it's _dependencies_ fails, so combinations of `runNextInputOnException` and `runNextDependencyOnException` should cover all your use cases.

**Comment by damianh** [comment]
Think I'll just have to experiment with some ideas here, see what sticks and what doesn't.

**Comment by adamralph** [comment]
OK, I'll keep this open for now, pending further insight.

**Comment by damianh** [comment]
We'll chat about this next week xx

**Comment by adamralph** [comment]
@damianh any more thoughts about this or shall we close?

**Comment by damianh** [comment]
Close. I'll come back to it when the itch needs scratching.

**Comment by lupin-de-mid** [comment]
Have any workaround for this?
I wish to to run tests as separate inputs, but fails fast is not very usefull

**Comment by adamralph** [comment]
@lupin-de-mid the only thing that springs to mind is looping through the inputs yourself instead, but then you'd only have a single target in the output, which kind of defeats the purpose of calling `dotnet test` separately for each input.

To do what you really want, Bullseye would have to do the collection of the exceptions from the inputs and fail the target at the end. It would have to be a new feature and a change in the API to allowing switching it on. I don't mind adding it, and I think [this](https://github.com/adamralph/bullseye/issues/373#issuecomment-552550792) would probably be the best way.
