### ISSUE TITLE
Broken output when piped through vagrant/winrm/powershell

### ISSUE THREAD

**Issue by ygel** [adamralph/bullseye#376]
## Version(s)

3.1.0-alpha.1

## To reproduce

It is complicated (tm): 
- VirtualBox with Server 2016
- Vagrant controls above via WinRM, running commands with PowerShell
- Gradle runs Vagrant above.

## Expected behavior

![image](https://user-images.githubusercontent.com/51912343/68829924-e1f09b80-066f-11ea-8b94-43e4695ec7bc.png)

## Actual behaviour

A clear and concise description of what did happen.
![image](https://user-images.githubusercontent.com/51912343/68829941-ed43c700-066f-11ea-8212-36e01f928e4e.png)

I suspect that those pretty lines don't go through the pipes very well.

**Comment by adamralph** [comment]
@ygel thanks for raising this, but I've no idea how to reproduce it. Vagrant, WinRM, Gradle... I think I've seen these words before, but that's as far as my understanding goes. 🙂

I'm surprised that the ANSI colour code sequences make it through the pipe, but the higher unicode chars do not. Is there anyway of fixing that somewhere in your pipeline?

If all else fails, I wouldn't be opposed to adding a new feature which provides an option to switch off the use of higher unicode chars. Bullseye already does this for Appveyor on Windows, so most of the code required is already present.

**Comment by ygel** [comment]
> If all else fails, I wouldn't be opposed to adding a new feature which provides an option to switch off the use of higher unicode chars. Bullseye already does this for Appveyor on Windows, so most of the code required is already present.

Thank you, I think most build runners have that option for one reason or another. It would be a good addition.

**Comment by ygel** [comment]
@adamralph  not much luck there, ultimately it's not a huge issue, feel free to close if it's not worth the effort to fix.

**Comment by adamralph** [comment]
@ygel I'm going to add the new option. This isn't a bug, so I'm closing it in favour of https://github.com/adamralph/bullseye/pull/393
