### ISSUE TITLE
Similar projects

### ISSUE THREAD

**Issue by mzorec** [adamralph/bullseye#379]
I see we have quite similar projects. I am co-author of https://github.com/dotnetcore/FlubuCore  
Would you be interested in joining "forces"? 

For now I won't go into details why I think this would be better. First I want to know if you are even willing to talk about it.

**Comment by adamralph** [comment]
@mzorec thanks for asking. I had a quick look at FlubuCore but it looks very different to Bullseye. Bullseye's main aim is simplicity, with a minimal API. It essentially consists of two methods: `Target` and `RunTargetsAndExit` (with a few overloads of each). FlubuCore seems to have many more things going on, and I'm not sure I need any of them, so I'm not sure that these are two projects which would consider merging.

**Comment by mzorec** [comment]
Yes that's true Flubu has to offer quite alot more features and built in tasks but if you look at both projects fundamental's then they are very similar. 

While Flubu has alot more going on it's up to the user to decide wheter he want's to use and/or need all those features. 
 Example that you have in readme for bullseye would look in Flubu something like this:

```c#
    public class BuildScript : DefaultBuildScript
    {
        protected override void ConfigureTargets(ITaskContext context)
        {
            context.CreateTarget("Example")
                .DependsOn(SomeOtherTarget)
                .Do((c) => { System.Console.WriteLine("Hello, world!"); });

        }
    }
```
I think that's very similar. We could also hide most of other features by introducing another base class for example:
` public class BuildScript : SimpleBuildScript`

Then it's up to the consumer to decide which base class he want's to use. There is ofcourse tons of other possibilites what could be done and I think merging both projects would bring quite alot of benefits both to us and to the consumers.

**Comment by adamralph** [comment]
The thing about Bullseye is that it is a _personal_ project. Sure, it has a permissive license and if anyone else finds it useful, great. But ultimately, it contains only the features that _I_ want, with a few small allowances.

So I have to consider what the benefit is to me of merging the projects. I don't need any of the features that Flubu has to offer over those in Bullseye, so I'm not seeing any benefit for me in merging the projects. All I see is the maintenance burden of features which I don't need.

I don't want to sound deliberately dismissive. This is my honest appraisal. If the projects were very similar, and the use cases they were solving overlapped almost entirely, then sure, I'd consider merging the projects. But what I see is that they are very different. Ultimately, Bullseye is just a library with two method groups, and they solve all my use cases. I have no need for anything else.

**Comment by mzorec** [comment]
Sure, no problem. I completly understand you. I had the felling in the beggining that your answer would be something like this. I asked anyway :)

Thank's for your time and good luck with the project.

**Comment by adamralph** [comment]
Thank you. Good luck with your Flubu too.
