### ISSUE TITLE
Implement RunTargetsAndReturnExitCode[Async]/RunTargetsAndReturnResult[Async]

### ISSUE THREAD

**Issue by teneko** [adamralph/bullseye#395]
## Use case(s)

Bullseye does calculate an exit code if called from RunTargetsAndExit[Async] and does quit. I am interested in the "exit code"/error and want to grab it. But the code is internal, so no chance to grab it. Did I miss something?

## Description

Let the user choose how to quit the program with context of failure. I am aware of the property `messageOnly`, but as I see, it is only invoked here https://github.com/adamralph/bullseye/blob/b177444ef5355dcab0bfa09526c5d70cda1361ad/Bullseye/Internal/ActionTarget.cs#L32. So you can measure, if there was an error, but do RunTargetsWithoutExiting does throw these errors up to the users? I did not have enough time to check that. So I would like to have something that gives me respond about my targets, something like a result, that contains exceptions/errors and "exit code"/status, when not already optionally thrown.

**Comment by adamralph** [comment]
@teroneko it should be enough to call `RunTargetsWithoutExiting` and catch exceptions. I.e.

```c#
try
{
    RunTargetsWithoutExiting(args);
}
catch(Exception ex)
{
   // do whatever you want here
}
```

The `messageOnly` parameter won't affect the exception being thrown, it's only used to determine how to log exceptions before throwing them.
