### ISSUE TITLE
Make args parsing public

### ISSUE THREAD

**Issue by adamralph** [adamralph/bullseye#396]
As per https://github.com/adamralph/bullseye/pull/393#issuecomment-576437222

**Comment by adamralph** [comment]
@ygel as we [previously discussed](https://github.com/adamralph/bullseye/pull/393#issuecomment-576406592), I've released this in [3.3.0-beta.1](https://www.nuget.org/packages/Bullseye/3.3.0-beta.1). Would you like to give it a try?

**Comment by ygel** [comment]
> Would you like to give it a try?

Thanks, will do! 
By the way, product repo I'm using this in has gone public: https://github.com/elastic/elastic-stack-installers

**Comment by adamralph** [comment]
hi @ygel, did you get a chance to try it out yet?

**Comment by adamralph** [comment]
@ygel I'm just going to release this. It's a low risk change.

**Comment by ygel** [comment]
My apologies, I was busy, then OOO for a some time, go ahead, I'll look at it anyway later on.
