### ISSUE TITLE
Optional teardown actions for targets

### ISSUE THREAD

**Issue by adamralph** [adamralph/bullseye#440]
## Use case

Sometimes targets set up resources that should be disposed of, such as running containers.

## Description

A new, optional, `Action teardown`/`Action<TInput> teardown`/`Func<Task> teardown`/`Func<TInput, Task> teardown` parameter on the appropriate `Target()` overloads. E.g.

```c#
Target(
    "foo",
    () => ...,    // set up some resources
    () => ...);   // tear down the resources
```

After all targets are executed, all registered teardown actions will be executed, in reverse order of registration. Teardown actions will be executed regardless of target success/failure.

**Comment by adamralph** [comment]
@damianh does this capture it?

**Comment by damianh** [comment]
It's a good start. Might you also need to support `Func<Task>` too?

**Comment by adamralph** [comment]
Good point. Yes, they will also be supported. In each overload, the type of the `teardown` parameter will match the type of the `action` parameter, and there are already overloads with `Func<Task> action`. I'll update the description.

**Comment by adamralph** [comment]
@damianh I started looking into implementing this but it does add considerable internal complexity. Right now I believe the ROI isn't worth it. Specially given that the use case is mostly satisfied today with `try...finally` in consuming code. I've also raised https://github.com/adamralph/bullseye/issues/470 which simply adds a single teardown action, effectively wrapping the boilerplate required for `try...finally`.

I'm closing this on that basis, but I've missed something then please let me know.

Incidentally, I may consider adding this as a "sponsored" feature, i.e. as paid work. If anyone is interested in getting a quote for that, please let me know.

**Comment by damianh** [comment]
Yeah fair enough 👍
