### ISSUE TITLE
Take a dep on System.CommandLine

### ISSUE THREAD

**Issue by adamralph** [adamralph/bullseye#558]
As soon as it's RTM: https://www.nuget.org/packages/System.CommandLine

(not yet decided whether to actually do this)

Depends on https://github.com/adamralph/bullseye/issues/532.

**Comment by alibresco** [comment]
I think this would be very valuable. System.CommandLine definitely seems like the direction MS wants to move in, and the current integration required for Bullseye users is very clunky.

**Comment by adamralph** [comment]
System.CommandLine looks abandoned. Last beta release was mid-2022. If it's ever revived, we can look into this again.
