### ISSUE TITLE
Add example or guide for single-file csx-based usage

### ISSUE THREAD

**Issue by nmehlei** [adamralph/bullseye#565]
## Use case(s)

In some use cases, it would be enough to have a single csx-based file that uses Bullseye, e.g. build.csx, which contains the different targets. This has the benefit of only needing a single file in the solutions' root directory instead of a dedicated project directory.

## Description

It's not completely self-explanatory how this is to be used in conjunction with Bullseye. A quickstart would be very helpful here.

**Comment by adamralph** [comment]
Hi @nmehlei, I have no interest in CSX, so it doesn't make sense for me to take on the burden of maintaining CSX examples. If you or someone else creates some CSX samples, I'd be happy to link to them from the README.
