### ISSUE TITLE
ForEach<string> doesn't fit with overloads without dependencies

### ISSUE THREAD

**Issue by adamralph** [adamralph/bullseye#67]
I realised this as I was writing the [new README.md](https://github.com/adamralph/bullseye/tree/90868435b6f35092b59c884c508a4fea3649bbcb#enumerable-inputs). 😿 

```C#
Target(
    "eat-biscuits",
    ForEach("digestives", "chocolate hob nobs"),
    biscuits => Console.WriteLine($"Mmm...{biscuits}! Nom nom."));
```

In this case the `name, dependsOn, action` overload is being called, and obviously targets named "digestives" and "chocolate hob nobs" are not found.

The fix is to add the parameter name (ugly):

```C#
Target(
    "eat-biscuits",
    forEach: ForEach("digestives", "chocolate hob nobs"),
    action: biscuits => Console.WriteLine($"Mmm...{biscuits}! Nom nom."));
```

And then it's better not to use `ForEach`, and use an array initializer instead (less ugly):

```C#
Target(
    "eat-biscuits",
    forEach: new[] {"digestives", "chocolate hob nobs"},
    action: biscuits => Console.WriteLine($"Mmm...{biscuits}! Nom nom."));
```

This issue may become "Deprecate DependsOn and ForEach". They were only added because C# doesn't have a pretty array initializer. I had a feeling they might come and bite me eventually.

**Comment by adamralph** [comment]
@blairconrad @thomaslevesque you've given some input on this before. What are your thoughts?

**Comment by blairconrad** [comment]
Thanks for asking!

Deprecating the helpers (or not, I suppose) and expecting users to use the parameter name would certainly work. Other options, off the top of my head:

1. Move the `forEach` parameter after `action`. It won't be confused with the dependencies, and if you _do_ put the param names or fancy convenience mehtods in at the call site, it still reads nicely.
2. Make `ForEach` and/or `DependsOn` return something that's not just an `IEnumerable`. Maybe a `ForEachList` or you know, whatever. Change the `Target` overloads (or add yet more overloads) to expect those. But then users always have to use those "helpers". This is going in a different direction than you want, I think, but I like it because I wanted more explicitness with the `forEach` parameter recently! It does restrict your ability to drop the helpers if/when C# gets a pretty array initializer, but maybe that's a problem for future Adam.

Um. That's all I got for now.

**Comment by thomaslevesque** [comment]
I like @blairconrad's second suggestion, I had something similar in mind. I guess `DependencyList` would work for dependencies, I'm not sure about `ForEachList`, though... Maybe `TargetParameterList`?

> It does restrict your ability to drop the helpers if/when C# gets a pretty array initializer, but maybe that's a problem for future Adam.

Not really an issue; you can always add an implicit conversion from array to the target type. It does constrain the type to be a class rather than an interface, since "user-defined conversions to or from an interface are not allowed" (CS0552)

**Comment by blairconrad** [comment]
> you can always add an implicit conversion from array to the target type

Of course! Where was my head?

**Comment by adamralph** [comment]
Thanks for the input!

Moving the params is a possibility, but the result feels a little unnatural. It feels more natural to "configure" the target at the beginning and have the "actual" target, i.e the stuff that happens, at the end.

Introducing the specific types would work too, but I'm hesitant for two reasons:

- A parameter type should be as wide as possible. I.e if all I need is `IEnumerable<string>` then that is exactly what the parameter type should be. I can then feed in a number of different concrete types as an argument.
- It makes the API less intuitive. If I see that the parameter type is `DependencyList`, the first thing I reach for is `new DependencyList(...)`. An implicit conversion from `IEnumerable<string>` is "invisible". I used to continuously struggle with this when using the MongoDB .NET client. It has things like implicit conversions from `string` to `MongoDBConnectionString` and I used to get in knots trying to construct those types instead of passing in the integral types.

Moreover, I'm cognizant of the fact that this entire conversation is happening just because I didn't like

```C#
new[] {"foo", "bar"}
```

as an array initializer. As we've discussed before, if C# allowed something like

```C#
["foo", "bar"]
```

I probably would never have introduced `DependsOn` (and then `ForEach`) in the first place. At this point I'm favouring sucking up my dislike for the verbose initializer and simplifying things by deprecating, and later removing, `DependsOn` and `ForEach` following a "less is more" philosophy.

BTW - when I said that non-trailing named arguments will be introduced in C# 8.0, I was mistaken. It was [introduced in C# 7.2](https://docs.microsoft.com/en-gb/dotnet/csharp/whats-new/csharp-7-2#non-trailing-named-arguments). That means the following will work today:

```C#
Target(
    "eat-biscuits",
    forEach: new[] {"digestives", "chocolate hob nobs"},
    action: biscuits => Console.WriteLine($"Mmm...{biscuits}! Nom nom."));
```

When you are using scripting for your build, the language version all depends on which version of the script runner you are using. But the beauty of using a regular C# project and `dotnet run` is that you can just add

**Comment by thomaslevesque** [comment]
> A parameter type should be as wide as possible. I.e if all I need is IEnumerable<string> then that is exactly what the parameter type should be. I can then feed in a number of different concrete types as an argument.

I would agree if this were a general purpose library, but Bullseye is really a DSL, so I think it's OK not to follow this principle in this case.

> It makes the API less intuitive.

True

> If I see that the parameter type is DependencyList, the first thing I reach for is new DependencyList(...)

Me, I often reach for `DependencyList.` and see if there's some kind of factory method. So I would probably see `DependsOn` in the suggestion list... if I have imported the `Targets` class with `using static`. But yeah, I guess it's not very easily discoverable.

**Comment by adamralph** [comment]
OK, so this is embarrassing. This entire issue was a massive brain fart. It's impossible for the wrong overload to be called, because those with `name, forEach, action` have the last parameter as `Action<TInput>` or `Func<TInput, Task>`.

The reason I thought this was a problem is that when I was writing the README sample, I initially copypasta'd from elsewhere and had something like this:

```C#
Target(
    "eat-biscuits",
    ForEach("digestives", "chocolate hob nobs"),
    () => Console.WriteLine(....));
```

I.e. the last argument was an `Action`, not `Action<string>`, so naturally the `string name, IEnumerable<string> dependsOn, Action action` overload was being called instead of the `string name, IEnumerable<string> forEach, Action<TInput> action` overload, which led me down the path of thinking that `dependsOn` and `forEach` were getting confused.

Highly embarrassing, and worse, time wasting. I apologise. 🙄

**Comment by blairconrad** [comment]
Like @thomaslevesque said. No worries. Glad it all worked out.
