### ISSUE TITLE
Typed dependencies

### ISSUE THREAD

**Issue by adamralph** [adamralph/bullseye#82]
As [suggested](http://disq.us/p/1vbdod3) by @pwhe23

**Comment by adamralph** [comment]
@pwhe23 I [implemented this](https://github.com/adamralph/bullseye/tree/typed-dependencies) and tried it out, but I'm convinced it adds much. E.g. compare these two versions of the LiteGuard build script:

## With `string` dependencies

```c#
Target("default", DependsOn("pack", "test"));

Target("build", () => RunAsync("dotnet", "build LiteGuard.sln --configuration Release"));

Target(
    "pack",
    DependsOn("build"),
    ForEach("LiteGuard.nuspec", "LiteGuard.Source.nuspec"),
    async nuspec =>
    {
        Environment.SetEnvironmentVariable("NUSPEC_FILE", nuspec, EnvironmentVariableTarget.Process);
        await RunAsync("dotnet", $"pack src/LiteGuard --configuration Release --no-build");
    });

Target(
    "test",
    DependsOn("build"),
    () => RunAsync("dotnet", $"test ./tests/LiteGuardTests/LiteGuardTests.csproj --configuration Release --no-build"));

return RunTargetsAsync(args);
```

## With typed dependencies

```c$
var build = Target("build", () => RunAsync("dotnet", "build LiteGuard.sln --configuration Release"));

var pack = Target(
    "pack",
    DependsOn(build),
    ForEach("LiteGuard.nuspec", "LiteGuard.Source.nuspec"),
    async nuspec =>
    {
        Environment.SetEnvironmentVariable("NUSPEC_FILE", nuspec, EnvironmentVariableTarget.Process);
        await RunAsync("dotnet", $"pack src/LiteGuard --configuration Release --no-build");
    });

var test = Target(
    "test",
    DependsOn(build),
    () => RunAsync("dotnet", $"test ./tests/LiteGuardTests/LiteGuardTests.csproj --configuration Release --no-build"));

var @default = Target("default", DependsOn(pack, test));

return RunTargetsAsync(args);
```

Some things to note about the typed dependency version:

- The targets _must_ be declared in the right order. E.g. The `default` target needs to go last.
- The code is more verbose
- The assignment of `@default` isn't actually required, but the API may lead people into thinking that it is (even though by the rules of the language, it can be implited that it isn't)
- The name of the `@default` variable is awkward, and needs the `@` prefix, since `default` is a C# keyword. It would be equally awkward to break the target name <-> variable name equality just for that case (not to mention that the variable isn't even required)

On balance, I'm not sure that this is is a better API. Note that I would not want to maintain two alternative APIs, so if this were to become the API, I would deprecate, and eventually remove, the string based API. Another thing to note is that the string based API is actually just as safe as the typed API, since Bullseye validates all the dependencies before running any targets. That means that any typo in a dependency name would be detected and an exception would be thrown. The only thing that is concretely missing with the string based API is Intellisense when defining the dependencies, but I'm not sure that small benefit is worth the costs listed above. Also, target dependency graphs don't tend to change often, and the number of targets is usually not very high, so the benfit of Intellisense for defining dependencies is limited.

I'm leaning towards closing this as a `wontfix`.

**Comment by pwhe23** [comment]
Sure, do whatever you think is best. We can always declare string constants if we don't want to repeat them.

**Comment by adamralph** [comment]
Thanks for the input @pwhe23
