### ISSUE TITLE
Cannot run a target with a name that another target name starts with

### ISSUE THREAD

**Issue by ronaldkroon** [adamralph/bullseye#820]
## Version(s)
4.1.0

## To reproduce
1. Define target `RunE2ETestsPurely`
2. Define target `RunE2ETests` (that depends on other targets and `RunE2ETestsPurely`)
3. Run with target `RunE2ETests`

## Expected behaviour
Execute target RunE2ETests with its dependencies.

## Actual behaviour
Error:
`Ambiguous target: RunE2ETests (RunE2ETestsPurely RunE2ETests)`

## Workarounds
Define targets without overlapping names

## Additional context
Introduced with https://github.com/adamralph/bullseye/commit/56904110a7609d49076dfd234bdca10551ad38e8

**Comment by adamralph** [comment]
Thank you for raising this @ronaldkroon. I'll fix it ASAP.

**Comment by adamralph** [comment]
@ronaldkroon the fix for this has been released in [4.1.1](https://www.nuget.org/packages/Bullseye/4.1.1). Thanks again!
