### ISSUE TITLE
Parallel does not parallelize the ForEach params in the Target when the target is run as a dependency

### ISSUE THREAD

**Issue by jakubsuchybio** [adamralph/bullseye#924]
## Version(s)
4.2.1

## To reproduce

Steps to reproduce the behaviour:

1. Have ForEach in a target
2. Use --parallel

## Expected behaviour
I would expect, that the ForEach should be able to run in parallel as well as the targets already can.

## Actual behaviour
The params from the ForEach are not ran in parallel

## Workarounds
Have multiple targets for different test projects, but that defeats the purpose of ForEach feature 

## Additional context
Test program:
```csharp
using System.Diagnostics;
using static Bullseye.Targets;

var startTime = Stopwatch.GetTimestamp();

Target("build", () =>
{
    Console.WriteLine("Building...");
});
Target("test1", DependsOn("build"), async () =>
{
    Console.WriteLine("Testing1...");
    await Task.Delay(1000);
});
Target("test2", DependsOn("build"), async () =>
{
    Console.WriteLine("Testing2...");
    await Task.Delay(1000);
});
Target("test3",
    DependsOn("build"), 
    ForEach("a", "b", "c"),
    async project =>
{
    Console.WriteLine($"Testing {project}...");
    await Task.Delay(1000);
});

Target("default", DependsOn("test1", "test2", "test3"), () =>
{
    Console.WriteLine($"Default... Elapsed: {Stopwatch.GetElapsedTime(startTime)}");
});

await RunTargetsAndExitAsync(args, ex => ex is SimpleExec.ExitCodeException);
```

Output:
![image](https://github.com/adamralph/bullseye/assets/6567287/5d101e1b-2d2c-4546-a1ad-896a9ca20672)

I would expect the Elapsed from the code to print something around 1.something second :)

My context is, that I'm just migrating teamcity pipeline, which has multiple configurations (jobs) that are written in cake, into gitlab ci. But we are still doing the parallelization at the pipeline level e.g. multiple jobs and so we have to handle transfering artifacts between the jobs, which is quite tedious and slowing the pipeline, because those jobs are ran in docker containers :( 
 
So I was thinking of simplifying the new gitlab pipeline into ONE job, which would then be parallelized at the C# code. And making it faster by even more so parallelizing test projects.. (cake and nuke don't even have parallelization for tasks/targets which you have)
I like your ForEach which would be used for parallelizing those test projects, but it is not parallel 😅

**Comment by adamralph** [comment]
@jakubsuchybio thanks for raising this! I believe #925 fixes it.

I'll push out a pre-release ASAP for you to test.

**Comment by adamralph** [comment]
@jakubsuchybio I just released [5.0.0 RC 1](https://www.nuget.org/packages/Bullseye/5.0.0-rc.1). Can you please give it a try to see if it solves the problem for you?

**Comment by jakubsuchybio** [comment]
Looks good, great! :)
![image](https://github.com/adamralph/bullseye/assets/6567287/75c7ed94-3aa5-464a-b200-52d01f0470e5)

**Comment by adamralph** [comment]
Excellent! I'll release 5.0.0 soon. In the meantime, please feel free to use 5.0.0 RC 1. Unless a new bug is found, 5.0.0 will be built from the same commit as 5.0.0 RC 1.
